### ISSUE TITLE
spring boot war에서 jar

### ISSUE THREAD

**Issue by jeonghwan951204** [jeonghwan951204/offside#1]
# 주제
스프링부트 실행 시 내장톰캣 사용

# 내용
스프링부트에 내장되어 있는 톰캣이 외장 WAS에 비하여 성능이 떨어지지 않는다고 함

# 참고 자료
https://okky.kr/article/636136

**Comment by jhy950210** [comment]
확인

**Comment by jhy950210** [comment]
리오픈
